#!/usr/bin/bash
#
# Source code checks.
#
# Run in src dir
# i.e. cd src
# 
# Requires:
# - pylint
# - pycodestyle
# - mypy

mod_dir='src/nginx_passwd_mod'
export PYTHONPATH=$(/usr/bin/realpath ./src)
    
# code
echo "Checking code"
/usr/bin/pylint $mod_dir/*py $mod_dir/*/*py 
/usr/bin/pycodestyle --max-line-length=110 $mod_dir/*py $mod_dir/*/*py
/usr/bin/mypy --check-untyped-defs --follow-untyped-imports $mod_dir

# Tests
echo ""
echo "---"
echo "Checking tests"
/usr/bin/pylint src/tests/*.py
/usr/bin/pycodestyle --max-line-length=110 src/tests/*.py
/usr/bin/mypy --check-untyped-defs --follow-untyped-imports src/tests

