#!/usr/bin/bash
#
# Source code checks.
#
# Run in src dir
# i.e. cd src
# 
# Requires:
# - pylint
# - pycodestyle
# - mypy

apps=(
    nginx-passwd.py
)

modules=(
    lib
)

mod_dir='nginx_passwd_mod'
    
# code
echo "---"
echo "Checking code"
PYTHONPATH=. pylint $mod_dir/*py $mod_dir/*/*py 
PYTHONPATH=. pycodestyle --max-line-length=110 $mod_dir/*py $mod_dir/*/*py
mypy --check-untyped-defs --follow-untyped-imports $mod_dir

# Tests
echo ""
echo "---"
echo "Checking tests"
cd ../tests
PYTHONPATH=../src pylint *py
PYTHONPATH=../src pycodestyle --max-line-length=110 *py
mypy --check-untyped-defs --follow-untyped-imports .

