#!/bin/bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2022,2023 Gene C
#
# installer script for nginx_passwd
# e.g. Call from PKGBUILD:  
#   ./do-install ${pkgdir}
# gene c (2022)
#
dest="$1"
self="nginx_passwd"

info="README.rst Docs scripts packaging "
infodir="/usr/share/${self}"

license="Docs/License/License.rst Docs/License/License-gpl-2.0.txt"
licensedir="/usr/share/licenses/${self}"

# list apps without the ".py" or leave empty string
apps=('nginx-passwd')

# so can make app link in /usr/bin
sitedir=$(/usr/bin/python3 -c "import site; print(site.getsitepackages()[0])")
installdir="${dest}${sitedir}"
app_location="${sitedir}/mkpkg_mod/apps"

uv_opts=(
    --python /usr/bin/python
    --system
    --no-build-isolation
    --link-mode=copy
    --compile-bytecode
)

if [ ! -d "$dest" ] ; then
    echo 'Missing destination directory'
    exit 1
else
    # shared

    /usr/bin/rsync --mkpath -a ${info} ${dest}${infodir}/
    /usr/bin/rsync --mkpath -a ${license} ${dest}/${licensedir}/

    /usr/bin/uv pip install ${uv_opts[@]} --target "$installdir" dist/*.whl
    /usr/bin/rm -rf "$installdir"/.lock

    # link(s) in /usr/bin/
    if [ -v apps ] ; then
        /usr/bin/mkdir -p "${dest}/usr/bin"
        for app in ${apps[@]}
        do
            /usr/bin/ln -sf ${app_location}/${app}.py ${dest}/usr/bin/${app}
        done
    fi
    exit 0
fi

